
version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    external_links:
     - externalredis
    networks:
     - default
networks:
  default:
    external:
      name: db_default
