version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile3
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - mongo
    container_name: mongoweb
  mongo:
    image: mongo
    ports:
     - "27018:27017"
    container_name: mongomongo
